---
title: "About Us"
---

Hangzhou Poly Packaging Co., Ltd. professionally deals with plastic packaging products and materials.

Our company has already been in the packaging filed since 1987 and we mainly specialize in woven poly mesh bags (onion bags), raschel bags, PE monofilament bags, FIBC bags (big bags), PP woven bags, carpet backing fabrics, mesh fabrics and pool covers. Our products are very popular in the markets of Europe, Australia and North America.

We hope that we can build up more friendly business relationships with various customers and friends around the world. We are able to supply you with the bags you ask for, not only for agricultural products, but also for industrial products.

The principle we always adhere to is "consistency in quality, timely delivery and competitive prices". Meanwhile, more than 4 other good factories are working with us closely and we have a strict quality control system. We hope that you will be happy with our excellent products and satisfactory services. 

In case of any question or inquiry, please do not hesitate to contact us right now.